import type { Metadata } from "next";
import { Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers/Providers";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar/Navbar";
import { fetchUserProfile } from "@/lib/serverActions/serverActions";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const profileData = await fetchUserProfile();

  return (
    <html lang="en">
      <body className={`${robotoMono.variable} ${geistMono.variable} bg-[#F4F2EE]`}>
        <Navbar user={profileData?.data?.user}/>
        <Providers>
          {children}
          <ToastContainer position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
